# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circunscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCircunscripcion', models.CharField(default=b'Desconocida', max_length=200)),
                ('numeroEscanhos', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMesa', models.CharField(default=b'Desconocida', max_length=200)),
                ('id_nombreCircunscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Circunscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePartido', models.CharField(default=b'Desconocido', max_length=200)),
                ('id_nombreCircunscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Circunscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resultado_Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Mesa')),
                ('id_resultadoM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Resultado')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado_Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.IntegerField(default=0)),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Partido')),
                ('id_resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Resultado')),
            ],
        ),
    ]
