# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circunscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCircunscripcion', models.CharField(default=b'Desconocida', max_length=200)),
                ('numeroEscanhos', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMesa', models.CharField(default=b'Desconocida', max_length=200)),
                ('id_nombreCircunscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa.Circunscripcion')),
            ],
        ),
    ]
